# Details
mod_author=Luken
mod_name=Ping Wheel
mod_id=pingwheel
archive_name=Ping-Wheel
contributors=RXJpaw
license=MIT
description=Mark locations similar to the ping mechanism found in modern co-op multiplayer games.
link_home=https://www.curseforge.com/minecraft/mc-mods/ping-wheel
link_src=https://github.com/LukenSkyne/Minecraft-Ping-Wheel
link_issues=https://github.com/LukenSkyne/Minecraft-Ping-Wheel/issues

# Common
mod_version=1.12.2

# Minecraft
minecraft_version=26.2
java_version=25

## This is the version of minecraft that the 'common' project uses, you can find a list of all versions here
## https://projects.neoforged.net/neoforged/neoform
neo_form_version=26.2-1

# ModDevGradle
# https://projects.neoforged.net/neoforged/moddevgradle
mod_dev_gradle_version=2.0.141

# Fabric
# https://fabricmc.net/develop/
fabric_version=0.154.2+26.2
fabric_loader_version=0.19.3
fabric_compatible_range=>=26.2 <=26.2
loom_version=1.17.14

# Forge
# https://files.minecraftforge.net/net/minecraftforge/forge/
net.minecraftforge.gradle.merge-source-sets=true
forge_version=65.0.4
forge_loader_version=65
forge_compatible_range=[26.2,26.2]

# NeoForge
# https://projects.neoforged.net/neoforged/neoforge
neoforge_version=26.2.0.18-beta
neoforge_loader_version=1
neoforge_compatible_range=[26.2,26.2]

# Integrations
modmenu_api_version=20.0.1
distanthorizons_api_version=5.1.0
voicechat_api_version=2.6.0
ftbteams_version=6930910

# Gradle
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false
