modLoader = "javafml"
loaderVersion = "[${neoforge_loader_version},)"
license = "${license}"
issueTrackerURL = "${link_issues}"

[[mods]]
modId = "${mod_id}"
version = "${version}"
displayName = "${mod_name}"
displayURL = "${link_src}"
iconFile = "icon.png"
authors = "${mod_author}, ${contributors}"
description = '''${description}'''
displayTest = "IGNORE_SERVER_VERSION"

[[mixins]]
config = "${mod_id}.mixins.json"

[[dependencies.${mod_id}]]
modId = "neoforge"
type = "required"
versionRange = "[${neoforge_version},)"
ordering = "NONE"
side = "BOTH"

[[dependencies.${mod_id}]]
modId = "minecraft"
type = "required"
versionRange = "${neoforge_compatible_range}"
ordering = "NONE"
side = "BOTH"
