name: "🚀 Deploy to Platforms"

on:
  workflow_dispatch:
    inputs:
      build_fabric:
        description: "Fabric"
        type: boolean
        default: true
      build_neoforge:
        description: "Neoforge"
        type: boolean
        default: true
      build_forge:
        description: "Forge"
        type: boolean
        default: true
      versions:
        description: "Versions"
        required: true
        type: string
        default: "1.18.2, 1.19.2, 1.19.3, 1.19.4, 1.20.1, 1.20.2, 1.20.4, 1.20.6, 1.21.1, 1.21.3, 1.21.4, 1.21.5, 1.21.8, 1.21.10, 1.21.11, 26.1.2"

jobs:
  prepare:
    name: "Prepare Matrix"
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - name: "Set matrix for build job"
        id: set-matrix
        run: |
          VERSIONS="${{ github.event.inputs.versions }}"
          MATRIX_JSON="{\"include\": ["

          # Create a list of versions
          for VERSION in $(echo $VERSIONS | sed "s/,/ /g")
          do
            MATRIX_JSON+="{\"version\": \"$VERSION\"},"
          done

          # Remove the last comma and close the JSON array
          MATRIX_JSON="${MATRIX_JSON%,}]}"

          echo "Matrix JSON: $MATRIX_JSON"
          echo "matrix=$MATRIX_JSON" >> $GITHUB_OUTPUT

  build:
    name: "Build"
    needs: prepare
    runs-on: ubuntu-latest
    strategy:
      matrix: ${{ fromJson(needs.prepare.outputs.matrix) }}
    steps:
      - name: "Check out repository"
        uses: actions/checkout@v6
        with:
          ref: ${{ matrix.version }}

      - name: "Extract gradle properties"
        run: |
          echo "JAVA_VERSION=$(awk -F'java_version=' '{print $2}' gradle.properties | xargs)" >> $GITHUB_ENV

      - name: "Set up JDK ${{ env.JAVA_VERSION }}"
        uses: actions/setup-java@v5
        with:
          distribution: "adopt"
          java-version: "${{ env.JAVA_VERSION }}"

      - name: "Build with Gradle"
        id: build
        run: chmod +x gradlew && ./gradlew build

      - name: "Archive build artifacts"
        uses: actions/upload-artifact@v7
        with:
          name: build-${{ matrix.version }}
          path: |
            ./fabric/build/libs
            ./neoforge/build/libs
            ./forge/build/libs
            CHANGELOG.md
            gradle.properties

  publish:
    name: "Publish"
    needs: [prepare, build]
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 1
      matrix: ${{ fromJson(needs.prepare.outputs.matrix) }}
    steps:
      - name: "Check out repository"
        uses: actions/checkout@v6
        with:
          sparse-checkout: |
            publish.gradle
          sparse-checkout-cone-mode: false
          ref: ${{ matrix.version }}

      - name: "Set up JDK 17"
        uses: actions/setup-java@v5
        with:
          distribution: "adopt"
          java-version: 17

      - name: "Setup Gradle 8.10"
        uses: gradle/actions/setup-gradle@v6
        with:
          add-job-summary: "never"
          gradle-version: "8.10"

      - name: "Download build artifacts"
        uses: actions/download-artifact@v8
        with:
          name: build-${{ matrix.version }}

      - name: "Extract gradle properties & prepare jars"
        run: |
          get_prop() {
            grep "^$1=" gradle.properties | cut -d'=' -f2- | xargs
          }

          ARCHIVE_NAME=$(get_prop "archive_name")
          MOD_VERSION=$(get_prop "mod_version")
          MC_VERSION=$(get_prop "minecraft_version")

          {
            echo "ARCHIVE_NAME=$ARCHIVE_NAME"
            echo "MOD_VERSION=$MOD_VERSION"
            echo "MC_VERSION=$MC_VERSION"
          } >> $GITHUB_ENV

          mkdir -p ./build/libs

          MAJOR=$(echo "$MC_VERSION" | cut -d'.' -f1)
          MINOR=$(echo "$MC_VERSION" | cut -d'.' -f2)

          LOADERS=()
          if [ "${{ inputs.build_fabric }}" == "true" ]; then LOADERS+=("fabric"); fi
          if [ "${{ inputs.build_neoforge }}" == "true" ]; then
            if [ "$MAJOR" -gt 1 ] || [ "$MINOR" -gt 20 ]; then
              LOADERS+=("neoforge")
            fi
          fi
          if [ "${{ inputs.build_forge }}" == "true" ]; then LOADERS+=("forge"); fi

          for LOADER in "${LOADERS[@]}"; do
            LOADER_UPPER=$(echo "$LOADER" | tr '[:lower:]' '[:upper:]')

            VERSION_RANGE=$(get_prop "${LOADER}_compatible_range")
            VERSION_START=$(echo "$VERSION_RANGE" | grep -oP '\d+\.\d+(?:\.\d+)?' | head -n 1)
            JAR_NAME="${ARCHIVE_NAME}-${MOD_VERSION}-${LOADER}-${MC_VERSION}"
            JAR_PATH="./build/libs/${JAR_NAME}.jar"

            {
              echo "${LOADER_UPPER}_VERSION_START=${VERSION_START}"
              echo "${LOADER_UPPER}_JAR_PATH=${JAR_PATH}"
            } >> $GITHUB_ENV

            mv "./${LOADER}/build/libs/${JAR_NAME}.jar" "$JAR_PATH"
          done

      - name: "Publish to Platforms"
        run: |
          echo "rootProject.buildFileName = 'publish.gradle'" > settings.gradle
          gradle publishMods
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          MODRINTH_TOKEN: ${{ secrets.MODRINTH_TOKEN }}
          CURSEFORGE_TOKEN: ${{ secrets.CURSEFORGE_TOKEN }}

          MODRINTH_PROJECT: "QQXAdCzh"
          CURSEFORGE_PROJECT: "734339"

          REF_NAME: ${{ matrix.version }}
